Sanger wgs variant calling@2.1.0 9.7.0
icgc-argo-workflows/sanger-wgs-variant-calling pull request #16
Opened 2023-05-17 15:03 UTC by lindaxiang

2023-06-13 19:18 UTC, edsu7 requested changes

2023-06-13 19:18 UTC, edsu7 commented on sanger-wgs-variant-calling/main.nf
> +include { payloadGenVariantCalling as pGenVarSnv; payloadGenVariantCalling as pGenVarIndel; payloadGenVariantCalling as pGenVarCnv; payloadGenVariantCalling as pGenVarSv; payloadGenVariantCalling as
should be:
```
./wfpr_modules/github.com/icgc-argo-workflows/data-processing-utility-tools/payload-gen-variant-calling@0.7.0/main.nf
```
instead of
```
./wfpr_modules/github.com/icgc-argo/data-processing-utility-tools/payload-gen-variant-calling@0.7.0/main.nf
```

2023-06-13 19:23 UTC, lindaxiang commented on sanger-wgs-variant-calling/main.nf
> +include { payloadGenVariantCalling as pGenVarSnv; payloadGenVariantCalling as pGenVarIndel; payloadGenVariantCalling as pGenVarCnv; payloadGenVariantCalling as pGenVarSv; payloadGenVariantCalling as
Good catch! Unbelievable, how comes I missed that?

2023-06-14 17:16 UTC, edsu7 approved these changes
lgtm

2023-06-29 18:37 UTC, merged